// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxPsbAG1D8e3eL9GAoEXWCoGlPSP2RT0',
    appId: '1:207005984967:web:1f51ab6eb0bcdc56bef6e2',
    messagingSenderId: '207005984967',
    projectId: 'aitransport-14dcf',
    authDomain: 'aitransport-14dcf.firebaseapp.com',
    storageBucket: 'aitransport-14dcf.firebasestorage.app',
    measurementId: 'G-1Y0WQZN9L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALIfPX61aTIKsFyAXSBh9DtIAIEdyS0Ho',
    appId: '1:207005984967:android:e4e7d3450d5c8760bef6e2',
    messagingSenderId: '207005984967',
    projectId: 'aitransport-14dcf',
    storageBucket: 'aitransport-14dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQXcRRA7zBk9V4d_-YqVjflCWJW0mTfI',
    appId: '1:207005984967:ios:5b805068a252bdebbef6e2',
    messagingSenderId: '207005984967',
    projectId: 'aitransport-14dcf',
    storageBucket: 'aitransport-14dcf.firebasestorage.app',
    iosBundleId: 'com.metafortech.iaparkingtra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcQXcRRA7zBk9V4d_-YqVjflCWJW0mTfI',
    appId: '1:207005984967:ios:5b805068a252bdebbef6e2',
    messagingSenderId: '207005984967',
    projectId: 'aitransport-14dcf',
    storageBucket: 'aitransport-14dcf.firebasestorage.app',
    iosBundleId: 'com.metafortech.iaparkingtra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgxPsbAG1D8e3eL9GAoEXWCoGlPSP2RT0',
    appId: '1:207005984967:web:ae08c6c888e26cd0bef6e2',
    messagingSenderId: '207005984967',
    projectId: 'aitransport-14dcf',
    authDomain: 'aitransport-14dcf.firebaseapp.com',
    storageBucket: 'aitransport-14dcf.firebasestorage.app',
    measurementId: 'G-GSD17Z3L69',
  );
}